#port-기본은 8080
server:
  port: 9003
  
#mysql  - driver-class-name 치면 나올거임
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-jbnnd-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp123!@#
    
#mybatis - mybatis.type.alias 머시기 
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml